USE [master]
GO

CREATE DATABASE [QandA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QandA', FILENAME = N'QandA.mdf' , SIZE = 262144KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QandA_log', FILENAME = N'QandA_log.ldf' , SIZE = 131072KB , MAXSIZE = 2048GB , FILEGROWTH = 32768KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QandA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QandA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QandA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QandA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QandA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QandA] SET ARITHABORT OFF 
GO

ALTER DATABASE [QandA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QandA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QandA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QandA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QandA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QandA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QandA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QandA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QandA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QandA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QandA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QandA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QandA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QandA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QandA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QandA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QandA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QandA] SET RECOVERY FULL 
GO

ALTER DATABASE [QandA] SET  MULTI_USER 
GO

ALTER DATABASE [QandA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QandA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QandA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QandA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QandA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QandA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QandA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QandA] SET  READ_WRITE 
GO


